### ISSUE TITLE
Multi-user functionality

### ISSUE THREAD

**Issue by Kegarver** [keighty/virtualplaybill2#129]
It would be cool if an individual could input a show, but then that show would go into a common database for others to pull from.

**Comment by keighty** [comment]
this is going to be huge:

* [ ] change datastore to mySQL
    * [ ] new tables: user, playbill
* [ ] use OAuth (google or facebook) instead of rolling our own

**Comment by keighty** [comment]
![vertabelo](https://cloud.githubusercontent.com/assets/1517356/12011933/3b540cc4-ac98-11e5-92fc-ad8423c70f7f.png)
